language: go
go: "1.12.x"
env:
  global:
    - GO111MODULE=on
install:
  - curl -sSfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.17.1
  - golangci-lint --version
script:
  - go test -race -p=8 -parallel=8 -coverpkg ./... -coverprofile=coverage.out ./...

  - golangci-lint run

  - echo "Check that go.mod and go.sum are tidy"
  - go mod tidy
  - if [[ `git status --porcelain go.mod` ]]; then git diff -- go.mod ; echo "go.mod is outdated, please run go mod tidy" ; exit 1; fi
  - if [[ `git status --porcelain go.sum` ]]; then git diff -- go.sum ; echo "go.sum is outdated, please run go mod tidy" ; exit 1; fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
